name: xencapture_usd2gltf
run-name: ${{ github.actor }} is building usd2gltf
on: [push]
jobs:
  xencapture_usd2gltf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: pip3 install build
      - name: Build package
        run: python3 -m build
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: "dist/usd2gltf-0.3.5-py3-none-any.whl, dist/usd2gltf-0.3.5.tar.gz"