name: xencapture_usd2gltf
run-name: ${{ github.actor }} is building usd2gltf
on: [push]
jobs:
  xencapture_usd2gltf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip3 install build
      - name: Build package
        run: python3 -m build
      - name: Archive whl
        uses: actions/upload-artifact@v4
        with:
          name: usd2gltf
          path: dist/usd2gltf-0.3.5-py3-none-any.whl
      - name: Archive tar
        uses: actions/upload-artifact@v4
        with:
          name: usd2gltf_tar
          path: dist/usd2gltf-0.3.5.tar.gz
        
